services:
  - type: web
    name: smartresume
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn smartresume.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
